const { buildDoc, writeDoc } = require("./kutlib");
const { renderKut } = require("./render");
const APPURL = "https://raptors-technology-free-tier-...cfapps.us10-001.hana.ondemand.com/pay/home";

const model = {
  guideMode: false,
  meta: { bpId: "BP-04", title: "Regular Payroll Dry Run", module: "Nabd Pay",
    version: "2.0", status: "Released", date: "July 2026", classification: "Internal — Project Use" },
  control: [
    ["Module", "Nabd Pay  ·  Payroll Runs"],
    ["Business process", "BP-04 — Regular Payroll Dry Run"],
    ["Document owner", "QA — Ahmed Salah"], ["Author", "QA — Ahmed Salah"],
    ["Reviewed by", "Payroll Consultants"], ["Approved by", "Delivery Lead"],
    ["Version", "2.0"], ["Status", "Released"],
    ["Environment", "Nabd Pay — QA tenant (" + APPURL + ")"],
    ["Classification", "Internal — Project Use"],
  ],
  revisions: [
    ["0.1", "02 Jun 2026", "Initial draft", "Ahmed Salah"],
    ["1.0", "18 Jun 2026", "Reviewed with consultants; released for KUT", "Ahmed Salah"],
    ["1.1", "07 Jul 2026", "Added Configuration section; tasks tagged by role", "Ahmed Salah"],
    ["2.0", "07 Jul 2026", "Reframed as pure training: removed prerequisites section and test/edge cases", "Ahmed Salah"],
  ],
  purpose: "The dry payroll run lets the Payroll Administrator compute a full pay cycle without posting to the general ledger or paying anyone. It is the normal step before the actual run: you review the figures and, once they look right, proceed to the actual run. This manual covers the whole process from start to finish — the one-time configuration that makes a dry run possible, then the steps to run it and read the results.",
  outcomes: [
    "Configure what a dry run needs — the cycle, population, roles and pay items.",
    "Run a complete dry payroll cycle end-to-end through the Run Wizard.",
    "Read and interpret the run results — Gross, Deductions, Net, Employer Cost and Taxable.",
    "Re-run the cycle to refresh the figures whenever the underlying data changes.",
  ],
  processInfo: [
    ["Trigger", "The pay cycle is open and ready to run."],
    ["Frequency", "Every pay period, before the actual run — and whenever figures change."],
    ["Roles involved", "Configuration Admin (one-time setup) and Payroll Administrator (runs & reviews)."],
    ["Inputs", "Open pay cycle, employee population, configured pay items and rules."],
    ["Outputs", "A dry-run result set — one result card per cycle — with headline totals."],
    ["Upstream / downstream", "Follows BP-03 Payroll Readiness; precedes BP-13 Actual Run, Approvals & Close."],
  ],
  roles: [
    ["Configuration Admin", "Config / Implementation role", "Performs the one-time setup: opens the cycle, assigns roles, confirms population and pay items."],
    ["Payroll Administrator", "Pay operator role", "Runs the dry payroll, reviews and records the results, and re-runs when figures change."],
  ],
  overview: [
    "Configure what the run needs — cycle, population, roles and pay items (one-time).",
    "Run the dry payroll through the Run Wizard: Scope → Preflight → Simulate → Review → Finish.",
    "Review and record the run totals.",
    "Re-run the cycle whenever the underlying figures change.",
  ],
  configIntro: "These one-time setup steps make the dry run possible. They are performed by the configuration team before key users run payroll. Once done, the Payroll Administrator can run the process repeatedly without repeating them.",
  configTasks: [
    { name: "Prepare the cycle, population, roles and pay items", role: "Configuration Admin",
      intro: "Set up everything the run needs. This is done once per environment; afterwards the Payroll Administrator runs the process on its own.",
      steps: [
        { action: "Open the target pay cycle.", nav: "Nabd Pay  ›  Control Center  ›  Cycles  ›  open the pay period",
          expected: "The target pay period shows as open and is available for selection in the Run Wizard.",
          screenshot: "Control Center with the target cycle open." },
        { action: "Confirm the employee population is replicated.", nav: "Left sidebar  ›  Employees",
          expected: "The full population is listed, replicated from the SuccessFactors tenant.",
          screenshot: "Employees list showing the population." },
        { action: "Assign the Payroll Administrator role.", nav: "SAP IAS  ›  Users & roles  ›  assign Payroll Administrator",
          expected: "The key user can act as Payroll Administrator in Nabd Pay.",
          note: "Roles are managed in SAP Identity Authentication, outside the Pay app.",
          screenshot: "IAS role assignment for the Payroll Administrator." },
        { action: "Confirm at least one earning pay item is configured.", nav: "Nabd Pay  ›  Config  ›  Component Studio",
          expected: "At least one earning pay item exists, so the run can compute pay.",
          screenshot: "Component Studio showing a configured earning pay item." },
      ] },
  ],
  tasks: [
    { name: "Run a dry payroll end-to-end", role: "Payroll Administrator",
      intro: "Run one complete dry payroll for the open cycle, from opening the wizard to the completion message.",
      steps: [
        { action: "Open Readiness and confirm the cycle is ready.", nav: "Nabd Pay  ›  Readiness",
          expected: "Readiness is green for the target cycle.",
          screenshot: "Readiness page showing the green “Ready to run” state." },
        { action: "Open the Payroll Runs list.", nav: "Left sidebar  ›  Runs",
          expected: "The “Payroll runs” page opens.",
          screenshot: "Payroll runs list page." },
        { action: "Start a new run.", nav: "Payroll runs  ›  New run",
          expected: "The Run Wizard opens on “Step 1 — Scope”.",
          screenshot: "Run Wizard open on the Scope step — circle the New run button." },
        { action: "Set the run mode to Dry run.", nav: "Run Wizard  ›  Run mode  ›  Dry run",
          expected: "The wizard is set to Dry run, so nothing is posted or paid.",
          screenshot: "Run-mode toggle set to Dry run." },
        { action: "Define the scope of the run.", nav: "Scope  ›  Pay period, Population, Scheme",
          expected: "“{count} employees in scope” shows the population count.",
          screenshot: "Scope step with pay period, population and the employee count." },
        { action: "Continue to Preflight.", nav: "Scope  ›  Continue",
          expected: "“Step 2 — Preflight” shows every check Ready: open cycle, employees in scope, pay items configured, rules authored.",
          screenshot: "Preflight step with all checks green." },
        { action: "Run the simulation.", nav: "Simulate  ›  Start simulation",
          expected: "Progress runs to “Done. N/N processed, 0 errors.”",
          screenshot: "Simulate step showing completion." },
        { action: "Review the results summary.", nav: "Simulate  ›  Continue  ›  Review",
          expected: "“Step 4 — Results summary” shows Employees, Gross, Deductions and Net payable (plus Employer Cost and Taxable).",
          screenshot: "Results summary with the headline totals." },
        { action: "Finish the dry run.", nav: "Review  ›  Continue  ›  Finish dry run",
          expected: "A confirmation appears: “Dry run complete — N employee(s)”.",
          screenshot: "The “Dry run complete” confirmation message." },
      ] },
    { name: "Review and record the run results", role: "Payroll Administrator",
      intro: "Read the result and note the headline totals so you can compare figures across runs.",
      steps: [
        { action: "Open the run and read the result.", nav: "Payroll runs  ›  open the run",
          expected: "The Verification panel (Gross, Deductions, Net, Employer Cost, Taxable Gross, SI Base, Valuation Basis) shows alongside the Earnings, Deductions and Employer-cost sections.",
          screenshot: "Opened run showing the Verification panel and result sections." },
        { action: "Record the headline totals.", nav: "Review step  /  run card",
          expected: "Employees, Gross, Deductions and Net are noted for reference.",
          screenshot: "Run card / review totals with the four figures highlighted." },
      ] },
  ],
  validation: [
    "The dry run completes with the confirmation “Dry run complete — N employee(s)”.",
    "The results summary shows Employees, Gross, Deductions and Net payable for the cycle.",
    "Opening the run shows the Verification panel and the Earnings / Deductions / Employer-cost sections.",
  ],
  troubleshooting: [
    ["“No open cycles” on the Scope step", "The pay cycle is not open yet.", "Open the cycle from Control Center (see Configuration), then return to the Run Wizard."],
    ["Preflight “Pay items configured” not ready", "No earning pay item exists for the population.", "Add at least one earning pay item in Component Studio (see Configuration), then re-check Preflight."],
    ["The employee count looks lower than expected", "The chosen population or scheme is narrower than intended.", "Go back to the Scope step and check the population and scheme selection."],
  ],
  tips: [
    { kind: "note", text: "A dry run never posts or pays anything. It is safe to run as often as you need to see up-to-date figures before the actual run." },
    { kind: "best", text: "Note the headline totals (Employees, Gross, Deductions, Net) after each run so you can see at a glance how figures change between runs." },
    { kind: "tip", text: "Whenever the underlying data changes — a new joiner, a pay change — simply run the dry payroll again to refresh the figures." },
  ],
  glossary: [
    ["Dry run", "A payroll calculation that computes results without posting to GL or paying anyone; safe to repeat."],
    ["Actual run", "A payroll run that, once approved, posts to the general ledger and feeds the bank file."],
    ["Readiness (BP-03)", "The pre-run view confirming master data, cycles, compliance and approvals are complete."],
    ["Preflight", "The Run Wizard's automatic pre-checks: open cycle, employees in scope, pay items, rules authored."],
    ["Verification panel", "The results block showing Gross, Deductions, Net, Employer Cost, Taxable Gross, SI Base and Valuation Basis."],
  ],
};

module.exports = { model };
if (require.main === module) (async () => { await writeDoc(buildDoc(model.meta, renderKut(model)), "BP-04_Regular_Payroll_Dry_Run_KUT.docx"); })();
